SCREEN_W = 1000
SCREEN_H = 600
FPS = 60
DATA_FONT_SIZE = 16
DATA_FONT_COLOUR = (0,0,0)

BACKGROUND_PATH = "images/background.png"
PADDLE_PATH = "images/paddle.png"
BALL_PATH = "images/ball.png"

PADDLE_SPEED = 500
DOWN_CHANCE = 1
UP_CHANCE = 2
PADDLE_COLLECTION_SIZE = 100

BALL_V = 200
BALL_H = -300

NNET_INPUTS = 2
NNET_HIDDEN = 15
NNET_OUTPUTS = 3

MAX_Y_DIFF = SCREEN_H
MIN_Y_DIFF = -SCREEN_H
Y_SHIFT = abs(MIN_Y_DIFF)
NORMALIZER = abs(MIN_Y_DIFF) + MAX_Y_DIFF

MUTATION_WEIGHT_MODIFY_CHANCE = 0.4
MUTATION_ARRAY_MIX_PERC = 0.5
MUTATION_CUT_OFF = 0.4
MUTATION_BAD_TO_KEEP = 0.2
MUTATION_MODIFY_CHANCE_LIMIT = 0.4

PADDLE_ALIVE = 0
PADDLE_DEAD = 1